version: '3.6'

services:
  adv_scum_web:
    container_name: adv_scum_web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/adv_scum/src
    working_dir: /usr/src/adv_scum/
    command: serve
    ports:
      - "8000:8000"
    networks:
      - default

#services:
#  mongodb:
#    image: mongo:latest
#    container_name: minduo_mongo_db
#    restart: unless-stopped
#    environment:
#      MONGO_INITDB_DATABASE: 'minduo'
#      MONGO_INITDB_ROOT_USERNAME: 'root'
#      MONGO_INITDB_ROOT_PASSWORD: 'password'
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./mongodb_data:/data/db
#      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
#    command: --auth
